version: '3.9'

services:
  db:
    image: 'postgres:13.2'
    environment:
      - POSTGRES_DB=emporium
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    command:
      - 'postgres'
      - '-c'
      - 'wal_level=logical'
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
  redis:
    image: 'redis:7.0.12'
    ports:
      - '6379:6379'
