import type { Jurisdiction } from '@prisma/client';

export const jurisdictions: Omit<Jurisdiction, 'id' | 'wareId'>[] = [
	{ abbreviation: 'al', name: 'alabama' },
	{ abbreviation: 'ak', name: 'alaska' },
	{ abbreviation: 'as', name: 'american samoa' },
	{ abbreviation: 'az', name: 'arizona' },
	{ abbreviation: 'ar', name: 'arkansas' },
	{ abbreviation: 'ca', name: 'california' },
	{ abbreviation: 'co', name: 'colorado' },
	{ abbreviation: 'ct', name: 'connecticut' },
	{ abbreviation: 'de', name: 'delaware' },
	{ abbreviation: 'dc', name: 'district of columbia' },
	{ abbreviation: 'fl', name: 'florida' },
	{ abbreviation: 'ga', name: 'georgia' },
	{ abbreviation: 'gu', name: 'guam' },
	{ abbreviation: 'hi', name: 'hawaii' },
	{ abbreviation: 'id', name: 'idaho' },
	{ abbreviation: 'il', name: 'illinois' },
	{ abbreviation: 'in', name: 'indiana' },
	{ abbreviation: 'ia', name: 'iowa' },
	{ abbreviation: 'ks', name: 'kansas' },
	{ abbreviation: 'ky', name: 'kentucky' },
	{ abbreviation: 'la', name: 'louisiana' },
	{ abbreviation: 'me', name: 'maine' },
	{ abbreviation: 'md', name: 'maryland' },
	{ abbreviation: 'ma', name: 'massachussetts' },
	{ abbreviation: 'mi', name: 'michigan' },
	{ abbreviation: 'mn', name: 'minnesota' },
	{ abbreviation: 'ms', name: 'mississippi' },
	{ abbreviation: 'mo', name: 'missouri' },
	{ abbreviation: 'mt', name: 'montana' },
	{ abbreviation: 'ne', name: 'nebraska' },
	{ abbreviation: 'nv', name: 'nevada' },
	{ abbreviation: 'nh', name: 'new hampshire' },
	{ abbreviation: 'nj', name: 'new jersey' },
	{ abbreviation: 'nm', name: 'new mexico' },
	{ abbreviation: 'ny', name: 'new york' },
	{ abbreviation: 'nc', name: 'north carolina' },
	{ abbreviation: 'nd', name: 'north dakota' },
	{ abbreviation: 'mp', name: 'northern mariana islands' },
	{ abbreviation: 'oh', name: 'ohio' },
	{ abbreviation: 'ok', name: 'oklahoma' },
	{ abbreviation: 'or', name: 'oregon' },
	{ abbreviation: 'pa', name: 'pennsylvania' },
	{ abbreviation: 'pr', name: 'puerto rico' },
	{ abbreviation: 'ri', name: 'rhode island' },
	{ abbreviation: 'sc', name: 'south carolina' },
	{ abbreviation: 'sd', name: 'south dakota' },
	{ abbreviation: 'tn', name: 'tennessee' },
	{ abbreviation: 'tx', name: 'texas' },
	{ abbreviation: 'ut', name: 'utah' },
	{ abbreviation: 'vt', name: 'vermont' },
	{ abbreviation: 'vi', name: 'us virgin islands' },
	{ abbreviation: 'va', name: 'virginia' },
	{ abbreviation: 'wa', name: 'washington' },
	{ abbreviation: 'wv', name: 'west virginia' },
	{ abbreviation: 'wi', name: 'wisconsin' },
	{ abbreviation: 'wy', name: 'wyoming' }
];
