"""empty message

Revision ID: 0b2c81977ade
Revises: eb6fffb085c0
Create Date: 2020-12-12 20:23:51.521941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b2c81977ade'
down_revision = 'eb6fffb085c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('question', sa.String(length=120), nullable=True),
    sa.Column('answer', sa.String(length=60), nullable=True),
    sa.Column('palette_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['palette_id'], ['palette.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trivia')
    # ### end Alembic commands ###
