"""content table

Revision ID: 44650fd29734
Revises: 
Create Date: 2020-11-22 22:04:52.744646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44650fd29734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary', sa.String(length=6), nullable=True),
    sa.Column('secondary', sa.String(length=6), nullable=True),
    sa.Column('accent', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=4), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Enum('video', 'audio', 'image', 'text', name='contenttype'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('palette', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['palette'], ['palette.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename', 'project_id')
    )
    op.create_index(op.f('ix_content_content_type'), 'content', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_created'), 'content', ['created'], unique=False)
    op.create_index(op.f('ix_content_palette'), 'content', ['palette'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_palette'), table_name='content')
    op.drop_index(op.f('ix_content_created'), table_name='content')
    op.drop_index(op.f('ix_content_content_type'), table_name='content')
    op.drop_table('content')
    op.drop_table('palette')
    # ### end Alembic commands ###
