"""change to media type

Revision ID: 4a229a2c5fdb
Revises: 21de6081db47
Create Date: 2020-11-29 18:56:05.980169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a229a2c5fdb'
down_revision = '21de6081db47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('media_type', sa.Enum('video', 'audio', 'image', 'text', name='mediatype'), nullable=False))
    op.create_index(op.f('ix_content_media_type'), 'content', ['media_type'], unique=False)
    op.drop_index('ix_content_content_type', table_name='content')
    op.drop_column('content', 'content_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('content_type', postgresql.ENUM('video', 'audio', 'image', 'text', name='filetype'), autoincrement=False, nullable=False))
    op.create_index('ix_content_content_type', 'content', ['content_type'], unique=False)
    op.drop_index(op.f('ix_content_media_type'), table_name='content')
    op.drop_column('content', 'media_type')
    # ### end Alembic commands ###
