"""main_content in project

Revision ID: c3e9c5f87777
Revises: 4a229a2c5fdb
Create Date: 2020-11-29 20:45:19.066843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3e9c5f87777'
down_revision = '4a229a2c5fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('main_content_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'project', 'content', ['main_content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'main_content_id')
    # ### end Alembic commands ###
