import os

# flask
FLASK_ENV = 'development'
SEND_FILE_MAX_AGE_DEFAULT = 0
SERVER_NAME = os.getenv('SERVER_NAME')
SECRET_KEY = os.getenv('SECRET_KEY')

# db
SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = False
MAX_CONTENT_LENGTH = 24 * 1024 * 1024 * 1024

# s3
CONTENT_HOME = os.getenv('CONTENT_HOME')
BOOTSTRAP_HOME = os.getenv('BOOTSTRAP_HOME')
DIST_HOME = os.getenv('DIST_HOME')

# cdn
CDN_URL = os.getenv('CDN_URL')

# aws
AWS_REGION = os.getenv('AWS_REGION')
AWS_VPC_ID = os.getenv('AWS_VPC_ID')
AWS_SUBNET_ID = os.getenv('AWS_SUBNET_ID')
